import moment from "moment";
import placeholder from "./pics/profilePic.png";

export default function data() {
  return {
    user: { uid: "290" },
    loading: false,
    accountType: "admin",
    address: "5 Beulah Avenue Trans Amadi",
    busStop: "amadi round about",
    country: "Nigeria",
    gender: "male",
    id: "837291871a",
    name: "Odili Road Satellite Church",
    occupation: "software developer",
    phoneNumber: "07080173071",
    profilePic: "",
    satelliteChurch: "odili road",
    serviceGroup: "technical",
    state: "Rivers state",
    testimonies: [
      {
        id: "ano1",
        satelliteChurch: "odili road",
        createdAt: moment(),
        text:
          "papa encouraged us to sow into the cathedral roofing project. I obeyed and sowed all my salary for the month of January 2020. Shortly after, God blesed me with a house and I was also sponsored by my organization for a training in India. I give God all the Glory.",
        title: "divine breakthrough",
        userId: "onnon2813ds",
        userName: "Shadrack Ibiso",
      },
      {
        id: "ano1",
        satelliteChurch: "odili road",
        createdAt: moment(),
        text:
          "papa encouraged us to sow into the cathedral roofing project. I obeyed and sowed all my salary for the month of January 2020. Shortly after, God blesed me with a house and I was also sponsored by my organization for a training in India. I give God all the Glory.",
        title: "divine breakthrough",
        userId: "onnon2813ds",
        userName: "Shadrack Ibiso",
      },
      {
        id: "ano1",
        satelliteChurch: "odili road",
        createdAt: moment(),
        text:
          "papa encouraged us to sow into the cathedral roofing project. I obeyed and sowed all my salary for the month of January 2020. Shortly after, God blesed me with a house and I was also sponsored by my organization for a training in India. I give God all the Glory.",
        title: "divine breakthrough",
        userId: "onnon2813ds",
        userName: "Shadrack Ibiso",
      },
      {
        id: "ano1",
        satelliteChurch: "odili road",
        createdAt: moment(),
        text:
          "papa encouraged us to sow into the cathedral roofing project. I obeyed and sowed all my salary for the month of January 2020. Shortly after, God blesed me with a house and I was also sponsored by my organization for a training in India. I give God all the Glory.",
        title: "divine breakthrough",
        userId: "onnon2813ds",
        userName: "Shadrack Ibiso",
      },
    ],
    soulsWon: [
      {
        address: "5 Beulah avenue Trans Amadi Port Harcourt",
        busStop: "amadi round about",
        createdAt: moment(),
        gender: "male",
        id: "23",
        name: "Shadrack Ibiso Deipriye Godswill",
        occupation: "software developer",
        phoneNumber: "07080173071",
        prayerRequest:
          "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Scripta periculis ei eam, te pro movet reformidans.",
        wonBy: "demo",
        wonThrough: "evangelism",
      },
      {
        address: "5 Beulah avenue Trans Amadi Port Harcourt",
        busStop: "amadi round about",
        createdAt: moment(),
        gender: "male",
        id: "23",
        name: "Shadrack Ibiso Deipriye Godswill",
        occupation: "software developer",
        phoneNumber: "07080173071",
        prayerRequest:
          "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Scripta periculis ei eam, te pro movet reformidans.",
        wonBy: "demo",
        wonThrough: "evangelism",
      },
      {
        address: "5 Beulah avenue Trans Amadi Port Harcourt",
        busStop: "amadi round about",
        createdAt: moment(),
        gender: "male",
        id: "23",
        name: "Shadrack Ibiso Deipriye Godswill",
        occupation: "software developer",
        phoneNumber: "07080173071",
        prayerRequest:
          "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Scripta periculis ei eam, te pro movet reformidans.",
        wonBy: "demo",
        wonThrough: "evangelism",
      },
      {
        address: "5 Beulah avenue Trans Amadi Port Harcourt",
        busStop: "amadi round about",
        createdAt: moment(),
        gender: "male",
        id: "23",
        name: "Shadrack Ibiso Deipriye Godswill",
        occupation: "software developer",
        phoneNumber: "07080173071",
        prayerRequest:
          "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Scripta periculis ei eam, te pro movet reformidans.",
        wonBy: "demo",
        wonThrough: "evangelism",
      },
      {
        address: "5 Beulah avenue Trans Amadi Port Harcourt",
        busStop: "amadi round about",
        createdAt: moment(),
        gender: "male",
        id: "23",
        name: "Shadrack Ibiso Deipriye",
        occupation: "software developer",
        phoneNumber: "07080173071",
        prayerRequest:
          "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Scripta periculis ei eam, te pro movet reformidans.",
        wonBy: "demo",
        wonThrough: "evangelism",
      },
      {
        address: "5 Beulah avenue Trans Amadi Port Harcourt",
        busStop: "amadi round about",
        createdAt: moment(),
        gender: "male",
        id: "23",
        name: "Shadrack Ibiso Deipriye",
        occupation: "software developer",
        phoneNumber: "07080173071",
        prayerRequest:
          "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Scripta periculis ei eam, te pro movet reformidans.",
        wonBy: "demo",
        wonThrough: "evangelism",
      },
      {
        address: "5 Beulah avenue Trans Amadi Port Harcourt",
        busStop: "amadi round about",
        createdAt: moment(),
        gender: "male",
        id: "23",
        name: "Shadrack Ibiso Deipriye",
        occupation: "software developer",
        phoneNumber: "07080173071",
        prayerRequest:
          "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Scripta periculis ei eam, te pro movet reformidans.",
        wonBy: "demo",
        wonThrough: "altarCall",
      },
      {
        address: "5 Beulah avenue Trans Amadi Port Harcourt",
        busStop: "amadi round about",
        createdAt: moment(),
        gender: "male",
        id: "23",
        name: "Shadrack Ibiso Deipriye",
        occupation: "software developer",
        phoneNumber: "07080173071",
        prayerRequest:
          "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Scripta periculis ei eam, te pro movet reformidans.",
        wonBy: "demo",
        wonThrough: "firstTimer",
      },
    ],
    notifications: [
      {
        createdAt: moment(),
        from: "odili road",
        id: "27",
        message: "There would be soul winning on Saturday by 9AM",
      },
      {
        createdAt: moment(),
        from: "odili road",
        id: "27",
        message: "There would be soul winning on Saturday by 9AM",
      },
      {
        createdAt: moment(),
        from: "odili road",
        id: "27",
        message: "There would be soul winning on Saturday by 9AM",
      },
      {
        createdAt: moment(),
        from: "odili road",
        id: "27",
        message: "There would be soul winning on Saturday by 9AM",
      },
      {
        createdAt: moment(),
        from: "odili road",
        id: "27",
        message: "There would be soul winning on Saturday by 9AM",
      },
      {
        createdAt: moment(),
        from: "odili road",
        id: "27",
        message: "There would be soul winning on Saturday by 9AM",
      },
    ],
    members: [
      {
        accountType: "admin",
        address: "5 Beulah avenue Trans Amadi Port Harcourt",
        busStop: "demo",
        country: "demo",
        gender: "male",
        id: "837291871a",
        name: "Abel Rufus Alfonsos",
        createdAt: moment(),
        occupation: "demo",
        phoneNumber: "demo",
        profilePic: "",
        satelliteChurch: "odili road",
        serviceGroup: "sanctuary",
        state: "Rivers state",
        soulsWon: 0,
      },
      {
        accountType: "admin",
        address: "demo",
        busStop: "demo",
        country: "demo",
        gender: "male",
        id: "837291871a",
        name: "Brenda Adoki",
        createdAt: moment(),
        occupation: "demo",
        phoneNumber: "demo",
        profilePic: "",
        satelliteChurch: "odili road",
        serviceGroup: "ushering",
        state: "Rivers state",
        soulsWon: 2,
      },
      {
        accountType: "admin",
        address: "demo",
        busStop: "demo",
        country: "demo",
        gender: "male",
        id: "837291871a",
        name: "Katherine Samson",
        createdAt: moment(),
        occupation: "demo",
        phoneNumber: "demo",
        profilePic: "",
        satelliteChurch: "odili road",
        serviceGroup: "ushering",
        state: "Rivers state",
        soulsWon: 3,
      },
      {
        accountType: "admin",
        address: "demo",
        busStop: "demo",
        country: "demo",
        gender: "male",
        id: "837291871a",
        name: "Natasha James",
        createdAt: moment(),
        occupation: "demo",
        phoneNumber: "demo",
        profilePic: "",
        satelliteChurch: "odili road",
        serviceGroup: "technical",
        state: "Rivers state",
        soulsWon: 5,
      },
      {
        accountType: "admin",
        address: "demo",
        busStop: "demo",
        country: "demo",
        gender: "male",
        id: "837291871a",
        name: "Eden Brook",
        createdAt: moment(),
        occupation: "demo",
        phoneNumber: "demo",
        profilePic: "",
        satelliteChurch: "odili road",
        serviceGroup: "technical",
        state: "Rivers state",
        soulsWon: 4,
      },
    ],
    slideShowPics: [
      { src: placeholder },
      { src: placeholder },
      { src: placeholder },
      { src: placeholder },
      { src: placeholder },
    ],
  };
}
