state = {
  user: { uid: "290" },
  loading: false,
  accountType: "admin",
  address: "demo",
  busStop: "demo",
  country: "demo",
  gender: "male",
  id: "837291871a",
  name: "demo",
  occupation: "demo",
  phoneNumber: "demo",
  profilePic: "",
  satelliteChurch: "odili road",
  serviceGroup: "none",
  state: "Rivers state",
  testimonies: [
    {
      id: "ano1",
      satelliteChurch: "odili road",
      createdAt: moment(),
      text:
        "papa encouraged us to sow into the cathedral roofing project. I obeyed and sowed all my salary for the month of January 2020. Shortly after, God blesed me with a house and I was also sponsored by my organization for a training in India. I give God all the Glory.",
      title: "divine breakthrough",
      userId: "onnon2813ds",
      userName: "Shadrack Ibiso",
    },
    {
      id: "ano1",
      satelliteChurch: "odili road",
      createdAt: moment(),
      text:
        "papa encouraged us to sow into the cathedral roofing project. I obeyed and sowed all my salary for the month of January 2020. Shortly after, God blesed me with a house and I was also sponsored by my organization for a training in India. I give God all the Glory.",
      title: "divine breakthrough",
      userId: "onnon2813ds",
      userName: "Shadrack Ibiso",
    },
    {
      id: "ano1",
      satelliteChurch: "odili road",
      createdAt: moment(),
      text:
        "papa encouraged us to sow into the cathedral roofing project. I obeyed and sowed all my salary for the month of January 2020. Shortly after, God blesed me with a house and I was also sponsored by my organization for a training in India. I give God all the Glory.",
      title: "divine breakthrough",
      userId: "onnon2813ds",
      userName: "Shadrack Ibiso",
    },
    {
      id: "ano1",
      satelliteChurch: "odili road",
      createdAt: moment(),
      text:
        "papa encouraged us to sow into the cathedral roofing project. I obeyed and sowed all my salary for the month of January 2020. Shortly after, God blesed me with a house and I was also sponsored by my organization for a training in India. I give God all the Glory.",
      title: "divine breakthrough",
      userId: "onnon2813ds",
      userName: "Shadrack Ibiso",
    },
  ],
  soulsWon: [
    {
      address: "5 Beulah avenue",
      busStop: "demo",
      gender: "demo",
      createdAt: moment(),
      gender: "male",
      id: "23",
      name: "demo",
      occupation: "demo",
      phoneNumber: "demo",
      prayerRequest: "demo",
      wonBy: "demo",
      wonThrough: "evangelism",
    },
    {
      address: "5 Beulah avenue",
      busStop: "demo",
      gender: "demo",
      createdAt: moment(),
      gender: "male",
      id: "23",
      name: "demo",
      occupation: "demo",
      phoneNumber: "demo",
      prayerRequest: "demo",
      wonBy: "demo",
      wonThrough: "evangelism",
    },
    {
      address: "5 Beulah avenue",
      busStop: "demo",
      gender: "demo",
      createdAt: moment(),
      gender: "male",
      id: "23",
      name: "demo",
      occupation: "demo",
      phoneNumber: "demo",
      prayerRequest: "demo",
      wonBy: "demo",
      wonThrough: "evangelism",
    },
    {
      address: "5 Beulah avenue",
      busStop: "demo",
      gender: "demo",
      createdAt: moment(),
      gender: "male",
      id: "23",
      name: "demo",
      occupation: "demo",
      phoneNumber: "demo",
      prayerRequest: "demo",
      wonBy: "demo",
      wonThrough: "evangelism",
    },
  ],
  notifications: [
    {
      createdAt: moment(),
      from: "odili road",
      id: "27",
      message: "There would be soul winning on Saturday by 9AM",
    },
    {
      createdAt: moment(),
      from: "odili road",
      id: "27",
      message: "There would be soul winning on Saturday by 9AM",
    },
  ],
  members: [
    {
      accountType: "admin",
      address: "demo",
      busStop: "demo",
      country: "demo",
      gender: "male",
      id: "837291871a",
      name: "demo",
      createdAt: moment(),
      occupation: "demo",
      phoneNumber: "demo",
      profilePic: "",
      satelliteChurch: "odili road",
      serviceGroup: "none",
      state: "Rivers state",
    },
    {
      accountType: "admin",
      address: "demo",
      busStop: "demo",
      country: "demo",
      gender: "male",
      id: "837291871a",
      name: "demo",
      createdAt: moment(),
      occupation: "demo",
      phoneNumber: "demo",
      profilePic: "",
      satelliteChurch: "odili road",
      serviceGroup: "none",
      state: "Rivers state",
    },
    {
      accountType: "admin",
      address: "demo",
      busStop: "demo",
      country: "demo",
      gender: "male",
      id: "837291871a",
      name: "demo",
      createdAt: moment(),
      occupation: "demo",
      phoneNumber: "demo",
      profilePic: "",
      satelliteChurch: "odili road",
      serviceGroup: "none",
      state: "Rivers state",
    },
    {
      accountType: "admin",
      address: "demo",
      busStop: "demo",
      country: "demo",
      gender: "male",
      id: "837291871a",
      name: "demo",
      createdAt: moment(),
      occupation: "demo",
      phoneNumber: "demo",
      profilePic: "",
      satelliteChurch: "odili road",
      serviceGroup: "none",
      state: "Rivers state",
    },
    {
      accountType: "admin",
      address: "demo",
      busStop: "demo",
      country: "demo",
      gender: "male",
      id: "837291871a",
      name: "demo",
      createdAt: moment(),
      occupation: "demo",
      phoneNumber: "demo",
      profilePic: "",
      satelliteChurch: "odili road",
      serviceGroup: "none",
      state: "Rivers state",
    },
  ],
  slideShowPics: [],
};
